/*
**	$Id$
**	Generated by IDLTool 53.6
**	Do not edit
**
**	AutoInit stub for kittyTurbo
**
**	Copyright (c) 2010 Hyperion Entertainment CVBA.
**	All Rights Reserved.
*/

#include <exec/types.h>
#include <libraries/kittyTurbo.h>

#include <interfaces/kittyTurbo.h>
#include <proto/exec.h>
#include <assert.h>

/****************************************************************************/

struct Library * kittyTurboBase = NULL;
static struct Library * __kittyTurboBase;

/****************************************************************************/

void kittyTurbo_base_constructor(void)
{
    if (kittyTurboBase != NULL)
    {
        return; /* Someone was quicker, e.g. an interface constructor */
    }
    __kittyTurboBase = kittyTurboBase = (struct Library *)IExec->OpenLibrary("kittyturbo.library", 0L);
    assert(kittyTurboBase != NULL);
}
__attribute__((section(".ctors.zzzz"))) static void
(*kittyTurbo_base_constructor_ptr)(void) USED = kittyTurbo_base_constructor;

/****************************************************************************/

void kittyTurbo_base_destructor(void)
{
    if (__kittyTurboBase)
    {
        IExec->CloseLibrary((struct Library *)__kittyTurboBase);
    }
}
__attribute__((section(".dtors.zzzz"))) static void
(*kittyTurbo_base_destructor_ptr)(void) USED = kittyTurbo_base_destructor;

/****************************************************************************/

