/*
**	$Id$
**	Generated by IDLTool 53.6
**	Do not edit
**
**	AutoInit stub for kittyTurbo
**
**	Copyright (c) 2010 Hyperion Entertainment CVBA.
**	All Rights Reserved.
*/

#include <exec/types.h>
#include <libraries/kittyTurbo.h>

#include <interfaces/kittyTurbo.h>
#include <proto/exec.h>
#include <assert.h>

struct kittyCompactIFace * IkittyTurbo = NULL;
static struct Library * __kittyTurboBase;
static struct kittyCompactIFace * __IkittyTurbo;

/****************************************************************************/

extern struct Library * kittyTurboBase;

/****************************************************************************/

void kittyTurbo_main_constructor(void)
{
    if (kittyTurboBase == NULL) /* Library base is NULL, we need to open it */
    {
        /* We were called before the base constructor.
         * This means we will be called _after_ the base destructor.
         * So we cant drop the interface _after_ closing the last library base,
         * we just open the library here which ensures that.
         */
        __kittyTurboBase = kittyTurboBase = (struct Library *)IExec->OpenLibrary("kittyturbo.library", 0L);
        assert(kittyTurboBase != NULL);
    }

    __IkittyTurbo = IkittyTurbo = (struct kittyCompactIFace *)IExec->GetInterface((struct Library *)kittyTurboBase, "main", 1, NULL);
    assert(IkittyTurbo != NULL);
}
__attribute__((section(".ctors.zzzy"))) static void
(*kittyTurbo_main_constructor_ptr)(void) USED = kittyTurbo_main_constructor;

/****************************************************************************/

void kittyTurbo_main_destructor(void)
{
    if (__IkittyTurbo)
    {
        IExec->DropInterface ((struct Interface *)__IkittyTurbo);
    }
    if (__kittyTurboBase)
    {
        IExec->CloseLibrary((struct Library *)__kittyTurboBase);
    }
}
__attribute__((section(".dtors.zzzy"))) static void
(*kittyTurbo_main_destructor_ptr)(void) USED = kittyTurbo_main_destructor;

/****************************************************************************/

