
/* This file was generated by idltool 53.6. Do not edit */

#include "kittyTurbo_vectors.h"

STATIC CONST APTR main_v1_vectors[] =
{
    _kittyturbo_Obtain,
    _kittyturbo_Release,
    NULL,
    NULL,
    _kittyturbo_makeLookupTable,
    _kittyturbo_FreeLookupTable,
    _kittyturbo_makeContext,
    _kittyturbo_FreeContext,
    (APTR)-1
};

