#ifndef INLINE4_KITTYTURBO_H
#define INLINE4_KITTYTURBO_H

/*
** This file was auto generated by idltool 53.6.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef LIBRARIES_KITTYTURBO_H
#include <libraries/kittyTurbo.h>
#endif
#include <interfaces/kittyTurbo.h>

/* Inline macros for Interface "main" */
#define makeLookupTable() IkittyTurbo->makeLookupTable() 
#define FreeLookupTable(table) IkittyTurbo->FreeLookupTable((table)) 
#define makeContext() IkittyTurbo->makeContext() 
#define FreeContext(table) IkittyTurbo->FreeContext((table)) 

#endif /* INLINE4_KITTYTURBO_H */
